-- SPDX-License-Identifier: GPL-2.0-or-later
---------------------------------------------------------------------------
-- BazUI shipped layout: Modern
--
-- One of the arrangements BazUI comes with, so somebody installing it has
-- something to choose between rather than one look to accept or rebuild
-- from nothing. Registered rather than applied: Core/Profiles.lua makes a
-- profile from each of these on a fresh install, and the Profiles page
-- can make another from one at any time.
--
-- Positions use screen anchors, never absolute pixels from a corner, so
-- the layout lands the same at any resolution.
--
-- Written by tools/bake-profiles.py from an arrangement made in game.
-- Editing it by hand is fine; the next bake will overwrite it.
-- Arranged on a 2100.5 x 1181.5 screen, baked 2026-09-19 20:00:06.
---------------------------------------------------------------------------

BazUI:RegisterPreset({
    id          = "Modern",
    name        = "Modern",
    description = "Rounded, roomier, and leaning on the newer art.",
    profile     = {
        Auras = {
            debuffBorders = true,
            enabled = true,
            hideBlizzard = true,
            iconShape = "square",
            iconSize = 40,
            perRow = 8,
            rows = {
                {
                    align = "LEFT",
                    dock = {
                        edge = "TOP",
                        host = "float",
                    },
                    dockedAs = "float",
                    filter = "HELPFUL",
                    gap = 4,
                    grow = "LEFT",
                    id = 1,
                    name = "Player Buffs 1",
                    onlyMine = false,
                    position = {
                        point = "CENTER",
                        relPoint = "TOPRIGHT",
                        x = -410.2,
                        y = -78.7,
                    },
                    stack = "DOWN",
                    takes = "half",
                    unit = "player",
                },
                {
                    align = "RIGHT",
                    dock = {
                        edge = "BOTTOM",
                        host = "aurarow:1",
                    },
                    dockSeq = 10,
                    dockedAs = "aurarow:1|BOTTOM",
                    filter = "HARMFUL",
                    gap = 19,
                    grow = "LEFT",
                    id = 2,
                    name = "Player Debuffs 1",
                    onlyMine = false,
                    position = {
                        point = "CENTER",
                        relPoint = "RIGHT",
                        x = -666.2,
                        y = 128,
                    },
                    stack = "DOWN",
                    takes = "full",
                    unit = "player",
                },
            },
            showCount = true,
            showDuration = true,
            showWeapons = true,
            sortDirection = "+",
            sortMethod = "INDEX",
            spacing = 3,
        },
        Bags = {
            bagMode = "categories",
            bgAlpha = 1,
            bgDarken = 0.4,
            bgTexture = "marble",
            categories = {
                consumables = {
                    isDefault = true,
                    matchMode = "any",
                    matchPriority = 20,
                    name = "Consumables",
                    order = 20,
                    tags = {
                        {
                            op = "equals",
                            type = "class",
                            value = 0,
                        },
                        {
                            op = "equals",
                            type = "class",
                            value = 6,
                        },
                    },
                },
                empty = {
                    isDefault = true,
                    isProtected = true,
                    matchMode = "all",
                    matchPriority = 1000,
                    name = "Empty Slots",
                    order = 70,
                    tags = {},
                },
                equipment = {
                    isDefault = true,
                    matchMode = "any",
                    matchPriority = 10,
                    name = "Equipment",
                    order = 10,
                    tags = {
                        {
                            op = "equals",
                            type = "class",
                            value = 2,
                        },
                        {
                            op = "equals",
                            type = "class",
                            value = 4,
                        },
                    },
                },
                junk = {
                    isDefault = true,
                    matchMode = "all",
                    matchPriority = 5,
                    name = "Junk",
                    order = 50,
                    tags = {
                        {
                            op = "=",
                            type = "quality",
                            value = 0,
                        },
                    },
                },
                keys = {
                    isDefault = true,
                    matchMode = "any",
                    matchPriority = 45,
                    name = "Keys",
                    order = 45,
                    tags = {
                        {
                            op = "equals",
                            type = "class",
                            value = 13,
                        },
                    },
                },
                other = {
                    isDefault = true,
                    isProtected = true,
                    matchMode = "all",
                    matchPriority = 999,
                    name = "Other",
                    order = 60,
                    tags = {},
                },
                questitems = {
                    isDefault = true,
                    matchMode = "any",
                    matchPriority = 40,
                    name = "Quest Items",
                    order = 40,
                    tags = {
                        {
                            op = "equals",
                            type = "class",
                            value = 12,
                        },
                    },
                },
                tradegoods = {
                    isDefault = true,
                    matchMode = "any",
                    matchPriority = 30,
                    name = "Trade Goods",
                    order = 30,
                    tags = {
                        {
                            op = "equals",
                            type = "class",
                            value = 7,
                        },
                        {
                            op = "equals",
                            type = "class",
                            value = 9,
                        },
                        {
                            op = "equals",
                            type = "class",
                            value = 3,
                        },
                        {
                            op = "equals",
                            type = "class",
                            value = 8,
                        },
                        {
                            op = "equals",
                            type = "class",
                            value = 5,
                        },
                    },
                },
            },
            cols = 10,
            customCategories = {},
            emptyBackdrop = true,
            goldOnly = false,
            hideBagBar = true,
            hideEmpty = true,
            itemCategories = {},
            maxRows = 15,
            perBagSections = true,
            position = {
                point = "RIGHT",
                relPoint = "RIGHT",
                x = -157.5,
                y = -97.6,
            },
            rarityRims = "uncommon",
            sellJunkButton = true,
            showBindType = false,
            showItemLevel = false,
            strata = "DIALOG",
            titleCount = true,
        },
        Bars = {
            autoFill = true,
            autoPlaceNew = true,
            bars = {
                {
                    alpha = 1,
                    cols = 24,
                    endcaps = "off",
                    endcapsAutoScale = false,
                    endcapsScale = 1,
                    id = 1,
                    locked = false,
                    mouseoverAlpha = 0.3,
                    mouseoverFade = false,
                    pos = {
                        point = "CENTER",
                        relPoint = "BOTTOM",
                        x = 0,
                        y = 33.2,
                    },
                    rightClickSelfCast = false,
                    rows = 1,
                    scale = 0.9,
                    spacing = 3,
                },
                {
                    alpha = 1,
                    cols = 8,
                    endcaps = "off",
                    endcapsAutoScale = false,
                    endcapsScale = 1,
                    id = 2,
                    locked = false,
                    mouseoverAlpha = 0.3,
                    mouseoverFade = false,
                    pos = {
                        point = "CENTER",
                        relPoint = "BOTTOM",
                        x = 0,
                        y = 467.7,
                    },
                    rightClickSelfCast = false,
                    rows = 2,
                    scale = 0.8,
                    spacing = 2,
                },
            },
            dragRequiresShift = false,
            fullRangeColor = true,
            hideDefaultActionBar = true,
            hideDefaultActionBarArt = false,
            hideStanceBar = true,
            showKeybindText = true,
            showMacroNames = true,
            showTooltips = true,
            stockRep = false,
            stockXP = false,
            tooltipAnchor = "default",
        },
        Chat = {
            channelNames = {
                enabled = true,
                shortNames = {
                    BATTLEGROUND = "bg",
                    BATTLEGROUND_LEADER = "bgl",
                    EMOTE = "e",
                    GUILD = "g",
                    INSTANCE_CHAT = "i",
                    INSTANCE_CHAT_LEADER = "il",
                    OFFICER = "o",
                    PARTY = "p",
                    PARTY_LEADER = "pl",
                    RAID = "r",
                    RAID_LEADER = "rl",
                    RAID_WARNING = "rw",
                    SAY = "s",
                    WHISPER = "w",
                    WHISPER_INFORM = "to",
                    YELL = "y",
                },
                stripChannelNumbers = true,
            },
            copyChat = {
                enabled = true,
                iconSize = 16,
            },
            docks = {
                dock = {
                    height = 160,
                    locked = true,
                    pos = {
                        point = "BOTTOMLEFT",
                        relPoint = "BOTTOMLEFT",
                        x = 18.3,
                        y = 35.5,
                    },
                    width = 399,
                },
            },
            enabled = true,
            loadBlizzardCombatLog = false,
            timestamps = {
                color = {
                    0.6,
                    0.6,
                    0.6,
                    1,
                },
                enabled = true,
                format = "%I:%M %p",
                hoverTooltip = true,
                separator = "-",
            },
            windows = {
                {
                    alpha = 1,
                    autoShow = "always",
                    bgAlpha = 0.8,
                    bgMode = "onhover",
                    channels = {
                        battleground = true,
                        bgLeader = true,
                        bnWhisper = true,
                        channel = true,
                        emote = true,
                        errors = true,
                        instance = true,
                        instanceLeader = true,
                        party = true,
                        partyLeader = true,
                        raid = true,
                        raidLeader = true,
                        raidWarning = true,
                        say = true,
                        system = true,
                        targetIcons = true,
                        whisper = true,
                        yell = true,
                    },
                    chromeFadeMode = "onhover",
                    customFont = true,
                    dockID = "dock",
                    eventGroup = "GENERAL",
                    fadeDuration = 0.5,
                    fading = true,
                    fontScale = 1,
                    indentedWordWrap = true,
                    label = "General",
                    maxLines = 500,
                    messageSpacing = 3,
                    scale = 1,
                    scrollbarMode = "onscroll",
                    tabsAlpha = 1,
                    tabsMode = "onhover",
                    timeVisible = 120,
                },
                {
                    alpha = 1,
                    autoShow = "guild",
                    bgMode = "onhover",
                    channels = {
                        guild = true,
                        officer = true,
                    },
                    chromeFadeMode = "onhover",
                    dockID = "dock",
                    eventGroup = "GUILD",
                    fadeDuration = 0.5,
                    fading = true,
                    indentedWordWrap = true,
                    label = "Guild",
                    maxLines = 500,
                    messageSpacing = 3,
                    scale = 1,
                    scrollbarMode = "onscroll",
                    tabsAlpha = 1,
                    tabsMode = "onhover",
                    timeVisible = 120,
                },
                {
                    alpha = 1,
                    autoShow = "city",
                    bgMode = "onhover",
                    channels = {
                        channel = true,
                        loot = true,
                    },
                    chromeFadeMode = "onhover",
                    dockID = "dock",
                    eventGroup = "LOOT",
                    fadeDuration = 0.5,
                    fading = true,
                    indentedWordWrap = true,
                    label = "Trade",
                    maxLines = 500,
                    messageSpacing = 3,
                    scale = 1,
                    scrollbarMode = "onscroll",
                    tabsAlpha = 1,
                    tabsMode = "onhover",
                    timeVisible = 120,
                },
                {
                    alpha = 1,
                    autoShow = "always",
                    bgMode = "onhover",
                    channels = {
                        combat = true,
                        skill = true,
                    },
                    chromeFadeMode = "onhover",
                    dockID = "dock",
                    eventGroup = "LOG",
                    fadeDuration = 0.5,
                    fading = true,
                    indentedWordWrap = true,
                    label = "Log",
                    maxLines = 500,
                    messageSpacing = 3,
                    scale = 1,
                    scrollbarMode = "onscroll",
                    tabsAlpha = 1,
                    tabsMode = "onhover",
                    timeVisible = 120,
                },
            },
        },
        Codex = {
            indexItems = true,
            itemCategory = "all",
            opacity = 1,
            position = {
                point = "CENTER",
                relPoint = "CENTER",
                x = -46.5,
                y = 83.7,
            },
            scale = 1,
        },
        Core = {
            modules = {},
        },
        Drawers = {
            backgroundOpacity = 0.9,
            broker = {
                autoEnableNew = true,
                emptyText = "-",
                showIcon = true,
                showLabel = true,
            },
            disableFadeInCombat = false,
            drawers = {
                default = {
                    autoSwitchEnabled = false,
                    icon = "Interface\\Icons\\INV_Misc_Gear_01",
                    label = "Default",
                    order = 1,
                    widgetOrder = {
                        bazdrawer_minimap = 20,
                        bazdrawer_minimapbuttons = 30,
                        bazdrawer_questtracker = 40,
                        bazdrawer_zonetext = 10,
                    },
                    widgets = "*",
                },
            },
            edgeRevealPx = 8,
            fadeDelay = 1,
            fadeDuration = 0.3,
            fadeEnabled = true,
            fadeTabWhenClosed = true,
            fadedOpacity = 0,
            frameOpacity = 1,
            locked = true,
            side = "right",
            transitionStyle = "instant",
            widgetDockedToBottom = {},
            widgetEnableStrict = true,
            widgetEnabled = {
                bazdrawer_minimap_infobar = false,
            },
            widgetFloating = {},
            widgetGlobalOverrides = {
                fadeBackground = {
                    enabled = false,
                },
                fadeTitleBar = {
                    enabled = false,
                },
            },
            widgetPositions = {},
            widgetSettings = {
                bazdrawer_minimap = {
                    frameStyle = "bazui",
                    hideDayNight = true,
                    hideZoomButtons = true,
                },
                bazdrawer_minimapbuttons = {
                    buttonStyle = "bazui",
                },
            },
            widgetSpacing = 6,
            width = 222,
        },
        MicroMenu = {
            buttonSize = 26,
            enabled = true,
            fadeAlpha = 0,
            hideBlizzard = true,
            mouseoverFade = false,
            orientation = "horizontal",
            position = {
                x = 520,
                y = -374.4,
            },
            spacing = 4,
        },
        Nameplates = {
            classColor = true,
            height = 10,
            kinds = {
                friendlyNpc = {
                    showBar = false,
                },
                friendlyPlayer = {
                    showBar = false,
                },
                tapped = {
                    showBar = true,
                },
            },
            nameSize = 9,
            showBar = true,
            showFriendly = true,
            showLevel = true,
            showName = true,
            showPlate = true,
            showRank = true,
            targetMark = true,
            width = 110,
        },
        Notifications = {
            bellAnchor = {
                point = "CENTER",
                relPoint = "TOPLEFT",
                x = 30.3,
                y = -30.7,
            },
            dndAutoCombat = false,
            dndAutoInstance = false,
            dndEnabled = false,
            historyRetentionDays = 7,
            maxHistory = 999,
            modules = {
                _bazui = {
                    enabled = true,
                },
                _test = {
                    enabled = true,
                },
            },
            panelOpacity = 0.9,
            position = "TOPLEFT",
            scale = 1,
            soundEnabled = true,
            soundHigh = 8959,
            soundLow = 0,
            soundNormal = 3175,
            toastDuration = 5,
            toastScale = 1,
            toastsEnabled = true,
            tomtomEnabled = true,
        },
        QoL = {
            restores = {},
            tweaks = {},
            windowPositions = {},
        },
        Tooltip = {
            anchor = "fixed",
            cursorX = 18,
            cursorY = 18,
            enabled = true,
            hideCombat = false,
            hideHealth = false,
            opacity = 1,
            origin = "auto",
            point = "BOTTOMRIGHT",
            scale = 1,
            skin = true,
            x = -132.6,
            y = 92.3,
        },
        UnitFrames = {
            barClicks = true,
            classColor = true,
            hidePlayerCastBar = true,
            hidePlayerFrame = true,
            position = {
                point = "CENTER",
                relPoint = "BOTTOM",
                x = 0,
                y = 190,
            },
            rangeAlpha = 0.5,
            rangeFade = true,
            rankGlow = true,
            rankIcon = true,
            rankWord = false,
            restIcon = true,
            showLevel = false,
            showValues = "hover",
            statusBars = {
                {
                    dock = {
                        edge = "LEFT",
                        host = "bar:2",
                    },
                    dockSeq = 16,
                    dockedAs = "bar:2|LEFT",
                    height = 53,
                    hoverFormat = "current/max",
                    id = 1,
                    indicators = {
                        combat = true,
                    },
                    kind = "health",
                    name = "Player Health 1",
                    position = {
                        point = "CENTER",
                        relPoint = "CENTER",
                        x = -260,
                        y = 80,
                    },
                    textFormat = "nameLevel",
                    textMode = "always",
                    textOutline = "THIN",
                    textSize = 16,
                    ticks = 0,
                    unit = "player",
                    width = 200,
                },
                {
                    dock = {
                        edge = "BOTTOM",
                        host = "statusbar:1",
                    },
                    dockSeq = 1,
                    dockedAs = "statusbar:1|BOTTOM",
                    height = 10,
                    hoverFormat = "current/max",
                    id = 2,
                    kind = "power",
                    name = "Player Power 1",
                    position = {
                        point = "CENTER",
                        relPoint = "CENTER",
                        x = -320,
                        y = -60,
                    },
                    textFormat = "current",
                    textMode = "hover",
                    ticks = 0,
                    unit = "player",
                    width = 200,
                },
                {
                    column = false,
                    dock = {
                        edge = "TOP",
                        host = "statusbar:1",
                    },
                    dockSeq = 2,
                    dockedAs = "statusbar:1|TOP",
                    height = 10,
                    id = 3,
                    kind = "cast",
                    name = "Player Casting 1",
                    position = {
                        point = "CENTER",
                        relPoint = "BOTTOMLEFT",
                        x = 570.3,
                        y = 370.8,
                    },
                    textFormat = "current",
                    textMode = "always",
                    ticks = 0,
                    unit = "player",
                    width = 200,
                },
                {
                    dock = {
                        edge = "RIGHT",
                        host = "bar:2",
                    },
                    dockSeq = 18,
                    dockedAs = "bar:2|RIGHT",
                    height = 65,
                    hoverFormat = "current/max",
                    id = 4,
                    kind = "health",
                    name = "Target Health 1",
                    position = {
                        point = "CENTER",
                        relPoint = "RIGHT",
                        x = -670.2,
                        y = -80,
                    },
                    textFormat = "nameLevel",
                    textMode = "always",
                    textShadow = true,
                    textSize = 16,
                    ticks = 0,
                    unit = "target",
                    width = 200,
                },
                {
                    align = "CENTER",
                    dock = {
                        edge = "TOP",
                        host = "bar:1",
                    },
                    dockSeq = 3,
                    dockedAs = "bar:1|TOP",
                    gap = 6,
                    height = 10,
                    id = 6,
                    kind = "xp",
                    name = "XP Bar 1",
                    position = {
                        point = "CENTER",
                        relPoint = "BOTTOM",
                        x = -64,
                        y = 142.8,
                    },
                    textFormat = "detailed",
                    textMode = "hover",
                    ticks = 10,
                    unit = "player",
                    width = 628,
                },
                {
                    dock = {
                        edge = "BOTTOM",
                        host = "float",
                    },
                    dockedAs = "float",
                    height = 24,
                    id = 7,
                    kind = "health",
                    name = "Party 1 Health 1",
                    position = {
                        point = "CENTER",
                        relPoint = "TOPLEFT",
                        x = 90.3,
                        y = -270.7,
                    },
                    textFormat = "namePercent",
                    textMode = "always",
                    ticks = 0,
                    unit = "party1",
                    width = 120,
                },
                {
                    dock = {
                        edge = "BOTTOM",
                        host = "statusbar:7",
                    },
                    dockSeq = 4,
                    dockedAs = "statusbar:7|BOTTOM",
                    height = 11,
                    id = 8,
                    kind = "power",
                    name = "Party 1 Power 1",
                    position = {
                        point = "CENTER",
                        relPoint = "CENTER",
                        x = 0,
                        y = -160,
                    },
                    textFormat = "current",
                    textMode = "always",
                    ticks = 0,
                    unit = "party1",
                    width = 240,
                },
                {
                    dock = {
                        edge = "BOTTOM",
                        host = "float",
                    },
                    dockedAs = "float",
                    height = 24,
                    id = 9,
                    kind = "health",
                    name = "Party 2 Health 2",
                    position = {
                        point = "CENTER",
                        relPoint = "TOPLEFT",
                        x = 90.3,
                        y = -339.7,
                    },
                    textFormat = "namePercent",
                    textMode = "always",
                    ticks = 0,
                    unit = "party2",
                    width = 120,
                },
                {
                    dock = {
                        edge = "BOTTOM",
                        host = "statusbar:9",
                    },
                    dockSeq = 5,
                    dockedAs = "statusbar:9|BOTTOM",
                    height = 11,
                    id = 10,
                    kind = "power",
                    name = "Party 2 Power 2",
                    position = {
                        point = "CENTER",
                        relPoint = "CENTER",
                        x = 0,
                        y = -160,
                    },
                    textFormat = "current",
                    textMode = "always",
                    ticks = 0,
                    unit = "party2",
                    width = 240,
                },
                {
                    dock = {
                        edge = "BOTTOM",
                        host = "float",
                    },
                    dockedAs = "float",
                    height = 24,
                    id = 11,
                    kind = "health",
                    name = "Party 3 Health 2",
                    position = {
                        point = "CENTER",
                        relPoint = "LEFT",
                        x = 90.3,
                        y = 182,
                    },
                    textFormat = "namePercent",
                    textMode = "always",
                    ticks = 0,
                    unit = "party3",
                    width = 120,
                },
                {
                    dock = {
                        edge = "BOTTOM",
                        host = "statusbar:11",
                    },
                    dockSeq = 6,
                    dockedAs = "statusbar:11|BOTTOM",
                    height = 11,
                    id = 12,
                    kind = "power",
                    name = "Party 3 Power 2",
                    position = {
                        point = "CENTER",
                        relPoint = "CENTER",
                        x = 0,
                        y = -160,
                    },
                    textFormat = "current",
                    textMode = "always",
                    ticks = 0,
                    unit = "party3",
                    width = 240,
                },
                {
                    dock = {
                        edge = "BOTTOM",
                        host = "float",
                    },
                    dockedAs = "float",
                    height = 24,
                    id = 13,
                    kind = "health",
                    name = "Party 4 Health 2",
                    position = {
                        point = "CENTER",
                        relPoint = "LEFT",
                        x = 90.3,
                        y = 113,
                    },
                    textFormat = "namePercent",
                    textMode = "always",
                    ticks = 0,
                    unit = "party4",
                    width = 120,
                },
                {
                    dock = {
                        edge = "BOTTOM",
                        host = "statusbar:13",
                    },
                    dockSeq = 7,
                    dockedAs = "statusbar:13|BOTTOM",
                    height = 11,
                    id = 14,
                    kind = "power",
                    name = "Party 4 Power 2",
                    position = {
                        point = "CENTER",
                        relPoint = "CENTER",
                        x = 0,
                        y = -160,
                    },
                    textFormat = "current",
                    textMode = "always",
                    ticks = 0,
                    unit = "party4",
                    width = 240,
                },
                {
                    dock = {
                        edge = "LEFT",
                        host = "statusbar:1",
                    },
                    dockSeq = 19,
                    dockedAs = "statusbar:1|LEFT",
                    height = 50,
                    id = 15,
                    kind = "portrait",
                    name = "Portrait Bar 1",
                    portrait3d = true,
                    position = {
                        point = "CENTER",
                        relPoint = "LEFT",
                        x = 570.3,
                        y = 60,
                    },
                    square = true,
                    textFormat = "namePercent",
                    textMode = "never",
                    ticks = 0,
                    unit = "player",
                    width = 10,
                },
                {
                    column = false,
                    dock = {
                        edge = "TOP",
                        host = "statusbar:4",
                    },
                    dockSeq = 8,
                    dockedAs = "statusbar:4|TOP",
                    height = 10,
                    id = 17,
                    kind = "cast",
                    name = "Target Casting 1",
                    position = {
                        point = "CENTER",
                        relPoint = "RIGHT",
                        x = -690.2,
                        y = 40,
                    },
                    textFormat = "current",
                    textMode = "always",
                    ticks = 0,
                    unit = "target",
                    width = 215,
                },
                {
                    dock = {
                        edge = "BOTTOM",
                        host = "statusbar:4",
                    },
                    dockSeq = 17,
                    dockedAs = "statusbar:4|BOTTOM",
                    height = 10,
                    id = 18,
                    kind = "power",
                    name = "Target Power 1",
                    position = {
                        point = "CENTER",
                        relPoint = "BOTTOMRIGHT",
                        x = -510.2,
                        y = 350.8,
                    },
                    textFormat = "current",
                    textMode = "always",
                    ticks = 0,
                    unit = "target",
                    width = 200,
                },
                {
                    dock = {
                        edge = "RIGHT",
                        host = "statusbar:4",
                    },
                    dockSeq = 23,
                    dockedAs = "statusbar:4|RIGHT",
                    height = 40,
                    id = 19,
                    kind = "portrait",
                    name = "Portrait Bar 2",
                    portrait3d = true,
                    position = {
                        point = "CENTER",
                        relPoint = "BOTTOMRIGHT",
                        x = -570.2,
                        y = 370.8,
                    },
                    square = true,
                    textFormat = "namePercent",
                    textMode = "never",
                    ticks = 0,
                    unit = "target",
                    width = 40,
                },
            },
            targetPosition = {
                point = "CENTER",
                relPoint = "TOP",
                x = 0,
                y = -80,
            },
            targetShowValues = "hover",
            unitTooltips = true,
        },
        skin = {
            active = "custom",
            custom = {
                border = {
                    {
                        color = {
                            0,
                            0,
                            0.1,
                            1,
                        },
                        thickness = 2,
                    },
                },
                colors = {
                    bg = {
                        0,
                        0,
                        0,
                        0.9,
                    },
                    bgHover = {
                        0.2,
                        0.1,
                        0.1,
                        0.9,
                    },
                    bgRaised = {
                        0.1,
                        0.1,
                        0.1,
                        0.9,
                    },
                    caution = {
                        1,
                        0.7,
                        0.2,
                        1,
                    },
                    danger = {
                        0.9,
                        0.3,
                        0.3,
                        1,
                    },
                    divider = {
                        0.6,
                        0.4,
                        0.2,
                        0.6,
                    },
                    edge = {
                        0.4,
                        0.3,
                        0.1,
                        0.6,
                    },
                    gold = {
                        1,
                        0.8,
                        0,
                        1,
                    },
                    goldDim = {
                        0.6,
                        0.5,
                        0.2,
                        1,
                    },
                    goldSoft = {
                        1,
                        0.8,
                        0.5,
                        1,
                    },
                    rankBoss = {
                        1,
                        0.4,
                        0.3,
                        0.9,
                    },
                    rankElite = {
                        1,
                        0.8,
                        0.3,
                        0.9,
                    },
                    rankRare = {
                        0.4,
                        0.7,
                        1,
                        0.9,
                    },
                    rankRareElite = {
                        0.7,
                        0.4,
                        1,
                        0.9,
                    },
                    success = {
                        0.5,
                        0.8,
                        0.5,
                        1,
                    },
                    text = {
                        1,
                        1,
                        0.9,
                        1,
                    },
                    textMuted = {
                        0.6,
                        0.6,
                        0.5,
                        1,
                    },
                    textSoft = {
                        0.8,
                        0.8,
                        0.6,
                        1,
                    },
                    warn = {
                        1,
                        0.5,
                        0.2,
                        1,
                    },
                },
                fill = "flat",
            },
        },
    },
})
