-- SPDX-License-Identifier: GPL-2.0-or-later
---------------------------------------------------------------------------
-- BazUI Starter Profile
--
-- The layout a fresh install starts with. Core lays these values over a
-- module's coded defaults the first time that module's section is
-- created in a profile: on a brand-new install, when a new profile is
-- made, and when a module is added to an existing install. Existing
-- sections are never touched, so nobody's settings change on update.
--
-- Positions use screen anchors (BOTTOM, TOP, RIGHT ...), never absolute
-- pixels from a corner, so the layout lands the same at any resolution
-- or UI scale.
--
-- Anything tied to one player stays out: per-character bar payloads,
-- item pins, chat history, minimap button order from other addons.
--
-- Written by tools/bake-starter.py from an arrangement made in game.
-- Editing it by hand is fine; the next bake will overwrite it.
-- Arranged on a 1920 x 1080 screen, 2026-09-18 06:22:42.
---------------------------------------------------------------------------

BazUI.StarterProfile = {
    Auras = {
        debuffBorders = true,
        enabled = true,
        hideBlizzard = true,
        iconSize = 40,
        perRow = 8,
        rows = {
            {
                align = "LEFT",
                dock = {
                    edge = "TOP",
                    host = "bar:1",
                },
                filter = "HELPFUL",
                gap = 4,
                id = 1,
                name = "Player Buffs 1",
                onlyMine = false,
                position = {
                    point = "CENTER",
                    relPoint = "BOTTOM",
                    x = -300,
                    y = 310,
                },
                takes = "half",
                unit = "player",
            },
            {
                align = "RIGHT",
                dock = {
                    edge = "TOP",
                    host = "bar:1",
                },
                filter = "HARMFUL",
                gap = 4,
                id = 2,
                name = "Player Debuffs 1",
                onlyMine = false,
                position = {
                    point = "CENTER",
                    relPoint = "BOTTOM",
                    x = -300,
                    y = 270,
                },
                takes = "half",
                unit = "player",
            },
            {
                align = "LEFT",
                dock = {
                    edge = "BOTTOM",
                    host = "statusbar:5",
                },
                filter = "HELPFUL",
                gap = 4,
                id = 3,
                maxRows = 1,
                name = "Target Buffs 1",
                onlyMine = false,
                position = {
                    point = "CENTER",
                    relPoint = "BOTTOM",
                    x = 300,
                    y = 310,
                },
                takes = "half",
                unit = "target",
            },
            {
                align = "RIGHT",
                dock = {
                    edge = "BOTTOM",
                    host = "statusbar:5",
                },
                filter = "HARMFUL",
                gap = 4,
                id = 4,
                maxRows = 1,
                name = "Target Debuffs 1",
                onlyMine = false,
                position = {
                    point = "CENTER",
                    relPoint = "BOTTOM",
                    x = 300,
                    y = 270,
                },
                takes = "half",
                unit = "target",
            },
        },
        showCount = true,
        showDuration = true,
        showWeapons = true,
        sortDirection = "+",
        sortMethod = "INDEX",
        spacing = 3,
    },
    Bags = {
        bagMode = "categories",
        bgAlpha = 1,
        bgDarken = 0.4,
        bgTexture = "marble",
        categories = {
            consumables = {
                isDefault = true,
                matchMode = "any",
                matchPriority = 20,
                name = "Consumables",
                order = 20,
                tags = {
                    {
                        op = "equals",
                        type = "class",
                        value = 0,
                    },
                    {
                        op = "equals",
                        type = "class",
                        value = 6,
                    },
                },
            },
            empty = {
                isDefault = true,
                isProtected = true,
                matchMode = "all",
                matchPriority = 1000,
                name = "Empty Slots",
                order = 70,
                tags = {},
            },
            equipment = {
                isDefault = true,
                matchMode = "any",
                matchPriority = 10,
                name = "Equipment",
                order = 10,
                tags = {
                    {
                        op = "equals",
                        type = "class",
                        value = 2,
                    },
                    {
                        op = "equals",
                        type = "class",
                        value = 4,
                    },
                },
            },
            junk = {
                isDefault = true,
                matchMode = "all",
                matchPriority = 5,
                name = "Junk",
                order = 50,
                tags = {
                    {
                        op = "=",
                        type = "quality",
                        value = 0,
                    },
                },
            },
            keys = {
                isDefault = true,
                matchMode = "any",
                matchPriority = 45,
                name = "Keys",
                order = 45,
                tags = {
                    {
                        op = "equals",
                        type = "class",
                        value = 13,
                    },
                },
            },
            other = {
                isDefault = true,
                isProtected = true,
                matchMode = "all",
                matchPriority = 999,
                name = "Other",
                order = 60,
                tags = {},
            },
            questitems = {
                isDefault = true,
                matchMode = "any",
                matchPriority = 40,
                name = "Quest Items",
                order = 40,
                tags = {
                    {
                        op = "equals",
                        type = "class",
                        value = 12,
                    },
                },
            },
            tradegoods = {
                isDefault = true,
                matchMode = "any",
                matchPriority = 30,
                name = "Trade Goods",
                order = 30,
                tags = {
                    {
                        op = "equals",
                        type = "class",
                        value = 7,
                    },
                    {
                        op = "equals",
                        type = "class",
                        value = 9,
                    },
                    {
                        op = "equals",
                        type = "class",
                        value = 3,
                    },
                    {
                        op = "equals",
                        type = "class",
                        value = 8,
                    },
                    {
                        op = "equals",
                        type = "class",
                        value = 5,
                    },
                },
            },
        },
        cols = 10,
        customCategories = {},
        emptyBackdrop = true,
        goldOnly = false,
        hideBagBar = true,
        hideEmpty = true,
        itemCategories = {},
        maxRows = 15,
        perBagSections = true,
        position = {
            point = "RIGHT",
            relPoint = "RIGHT",
            x = -285,
            y = -18,
        },
        rarityRims = "uncommon",
        sellJunkButton = true,
        showBindType = false,
        showItemLevel = false,
        strata = "DIALOG",
        titleCount = true,
    },
    Bars = {
        autoFill = true,
        autoPlaceNew = true,
        bars = {
            {
                alpha = 1,
                cols = 14,
                endcaps = "off",
                endcapsAutoScale = false,
                endcapsScale = 1,
                id = 1,
                locked = false,
                mouseoverAlpha = 0.3,
                mouseoverFade = false,
                pos = {
                    point = "CENTER",
                    relPoint = "BOTTOM",
                    x = 0,
                    y = 85.7,
                },
                rightClickSelfCast = false,
                rows = 1,
                scale = 0.7,
                spacing = 3,
            },
            {
                alpha = 1,
                cols = 8,
                endcaps = "off",
                endcapsAutoScale = false,
                endcapsScale = 1,
                id = 2,
                locked = false,
                mouseoverAlpha = 0.3,
                mouseoverFade = false,
                pos = {
                    point = "CENTER",
                    relPoint = "BOTTOM",
                    x = 0,
                    y = 451.4,
                },
                rightClickSelfCast = false,
                rows = 2,
                scale = 0.7,
                spacing = 3,
            },
        },
        dragRequiresShift = false,
        fullRangeColor = true,
        hideDefaultActionBar = true,
        hideDefaultActionBarArt = false,
        hideStanceBar = true,
        showKeybindText = true,
        showMacroNames = true,
        showTooltips = true,
        stockRep = false,
        stockXP = false,
        tooltipAnchor = "default",
    },
    Codex = {
        indexItems = true,
        itemCategory = "all",
        opacity = 1,
        scale = 1,
    },
    Core = {
        modules = {},
    },
    Drawers = {
        backgroundOpacity = 0.9,
        broker = {
            autoEnableNew = true,
            emptyText = "-",
            showIcon = true,
            showLabel = true,
        },
        disableFadeInCombat = false,
        drawers = {
            default = {
                autoSwitchEnabled = false,
                icon = "Interface\\Icons\\INV_Misc_Gear_01",
                label = "Default",
                order = 1,
                widgetOrder = {
                    bazdrawer_minimap = 20,
                    bazdrawer_minimapbuttons = 30,
                    bazdrawer_questtracker = 40,
                    bazdrawer_zonetext = 10,
                },
                widgets = "*",
            },
        },
        edgeRevealPx = 8,
        fadeDelay = 1,
        fadeDuration = 0.3,
        fadeEnabled = true,
        fadeTabWhenClosed = true,
        fadedOpacity = 0,
        frameOpacity = 1,
        locked = true,
        side = "right",
        transitionStyle = "instant",
        widgetDockedToBottom = {},
        widgetEnableStrict = true,
        widgetEnabled = {
            bazdrawer_minimap_infobar = false,
        },
        widgetFloating = {},
        widgetGlobalOverrides = {},
        widgetPositions = {},
        widgetSettings = {
            bazdrawer_minimap = {
                frameStyle = "bazui",
                hideDayNight = true,
                hideZoomButtons = true,
            },
            bazdrawer_minimapbuttons = {
                buttonStyle = "bazui",
            },
        },
        widgetSpacing = 6,
        width = 222,
    },
    MicroMenu = {
        buttonSize = 26,
        enabled = true,
        fadeAlpha = 0,
        hideBlizzard = true,
        mouseoverFade = true,
        orientation = "horizontal",
        position = {
            point = "TOP",
            relPoint = "TOP",
            x = 0,
            y = -4,
        },
        spacing = 4,
    },
    Nameplates = {
        classColor = true,
        height = 10,
        nameSize = 9,
        showFriendly = true,
        showLevel = true,
        showRank = true,
        targetMark = true,
        width = 110,
    },
    Notifications = {
        dndAutoCombat = false,
        dndAutoInstance = false,
        dndEnabled = false,
        historyRetentionDays = 7,
        maxHistory = 999,
        modules = {
            _bazui = {
                enabled = true,
            },
            _test = {
                enabled = true,
            },
        },
        panelOpacity = 0.9,
        position = "TOPLEFT",
        scale = 1,
        soundEnabled = true,
        soundHigh = 8959,
        soundLow = 0,
        soundNormal = 3175,
        toastDuration = 5,
        toastScale = 1,
        toastsEnabled = true,
        tomtomEnabled = true,
    },
    QoL = {
        restores = {},
        tweaks = {},
    },
    Tooltip = {
        anchor = "default",
        cursorX = 18,
        cursorY = 18,
        enabled = true,
        hideCombat = false,
        hideHealth = false,
        opacity = 1,
        origin = "auto",
        point = "BOTTOMRIGHT",
        scale = 1,
        skin = true,
        x = -24,
        y = 100,
    },
    UnitFrames = {
        barClicks = true,
        classColor = true,
        hidePlayerCastBar = true,
        hidePlayerFrame = true,
        position = {
            point = "CENTER",
            relPoint = "BOTTOM",
            x = 0,
            y = 190,
        },
        rangeAlpha = 0.5,
        rangeFade = true,
        rankGlow = true,
        rankIcon = true,
        rankWord = false,
        restIcon = true,
        showLevel = false,
        showValues = "hover",
        statusBars = {
            {
                dock = {
                    edge = "BOTTOM",
                    host = "bar:2",
                },
                height = 24,
                hoverFormat = "current/max",
                id = 1,
                kind = "health",
                name = "Player Health 1",
                position = {
                    point = "CENTER",
                    relPoint = "BOTTOM",
                    x = -256,
                    y = 220,
                },
                textFormat = "nameLevel",
                textMode = "always",
                ticks = 0,
                unit = "player",
                width = 240,
            },
            {
                dock = {
                    edge = "BOTTOM",
                    host = "statusbar:1",
                },
                height = 10,
                id = 2,
                kind = "power",
                name = "Player Power 1",
                position = {
                    point = "CENTER",
                    relPoint = "CENTER",
                    x = 0,
                    y = -160,
                },
                textFormat = "current",
                textMode = "always",
                ticks = 0,
                unit = "player",
                width = 240,
            },
            {
                dock = {
                    edge = "TOP",
                    host = "bar:2",
                },
                height = 10,
                id = 3,
                kind = "cast",
                name = "Player Casting 1",
                position = {
                    point = "CENTER",
                    relPoint = "CENTER",
                    x = -96,
                    y = 96,
                },
                textFormat = "current",
                textMode = "always",
                ticks = 0,
                unit = "player",
                width = 240,
            },
            {
                dock = {
                    edge = "BOTTOM",
                    host = "float",
                },
                height = 24,
                id = 4,
                kind = "health",
                name = "Target Health 1",
                position = {
                    point = "CENTER",
                    relPoint = "TOP",
                    x = 0,
                    y = -60,
                },
                textFormat = "namePercent",
                textMode = "always",
                ticks = 0,
                unit = "target",
                width = 240,
            },
            {
                dock = {
                    edge = "BOTTOM",
                    host = "statusbar:4",
                },
                height = 10,
                id = 5,
                kind = "power",
                name = "Target Power 1",
                position = {
                    point = "CENTER",
                    relPoint = "CENTER",
                    x = 0,
                    y = -160,
                },
                textFormat = "current",
                textMode = "always",
                ticks = 0,
                unit = "target",
                width = 240,
            },
            {
                align = "CENTER",
                dock = {
                    edge = "BOTTOM",
                    host = "bar:1",
                },
                gap = 6,
                height = 10,
                id = 6,
                kind = "xp",
                name = "XP Bar 1",
                position = {
                    point = "CENTER",
                    relPoint = "CENTER",
                    x = 0,
                    y = -160,
                },
                textFormat = "detailed",
                textMode = "hover",
                ticks = 10,
                unit = "player",
                width = 240,
            },
        },
        targetPosition = {
            point = "CENTER",
            relPoint = "TOP",
            x = 0,
            y = -80,
        },
        targetShowValues = "hover",
        unitTooltips = true,
    },
}
