-- SPDX-License-Identifier: GPL-2.0-or-later
---------------------------------------------------------------------------
-- BazUI Codex: the factions there are
--
-- GENERATED by tools/gen-factions.py from the game's Faction table for
-- build 1.60.1.69893. Do not edit by hand; run the tool.
--
-- The client lists only the factions this character has met. This is
-- the rest of them, so the Reputation page can show what you have not
-- met yet - greyed, with live standing read by id.
--
-- Ids, not names. The client supplies the name in your language, and
-- it confirms each entry at load: a faction it has no description for
-- is a creature faction or a leftover, not a reputation, and is left
-- out; the other side's cities it does not answer for at all. So a
-- wrong id here hides itself rather than lying.
--
-- The groups are the words the game's own pane uses as headers. Where
-- a faction already met sits under a header, its unmet neighbours join
-- it under that header, whatever the client calls it; the words here
-- are only the fallback when nothing in the group has been met yet.
---------------------------------------------------------------------------

local Codex = BazUI.Codex
Codex.Factions = Codex.Factions or {}
local Factions = Codex.Factions

Factions.build = "1.60.1.69893"

Factions.entries = {
    -- Alliance
    { id = 69, group = "Alliance" },   -- Darnassus
    { id = 54, group = "Alliance" },   -- Gnomeregan Exiles
    { id = 47, group = "Alliance" },   -- Ironforge
    { id = 72, group = "Alliance" },   -- Stormwind

    -- Horde
    { id = 530, group = "Horde" },   -- Darkspear Trolls
    { id = 76, group = "Horde" },   -- Orgrimmar
    { id = 81, group = "Horde" },   -- Thunder Bluff
    { id = 68, group = "Horde" },   -- Undercity

    -- Alliance Forces
    { id = 890, group = "Alliance Forces" },   -- Silverwing Sentinels
    { id = 730, group = "Alliance Forces" },   -- Stormpike Guard
    { id = 509, group = "Alliance Forces" },   -- The League of Arathor
    { id = 2799, group = "Alliance Forces" },   -- Theramore Expeditionary Force

    -- Horde Forces
    { id = 2798, group = "Horde Forces" },   -- Darkspear Raiders
    { id = 729, group = "Horde Forces" },   -- Frostwolf Clan
    { id = 510, group = "Horde Forces" },   -- The Defilers
    { id = 889, group = "Horde Forces" },   -- Warsong Outriders

    -- Steamwheedle Cartel
    { id = 21, group = "Steamwheedle Cartel" },   -- Booty Bay
    { id = 577, group = "Steamwheedle Cartel" },   -- Everlook
    { id = 369, group = "Steamwheedle Cartel" },   -- Gadgetzan
    { id = 2827, group = "Steamwheedle Cartel" },   -- Powderfuse
    { id = 470, group = "Steamwheedle Cartel" },   -- Ratchet

    -- Other
    { id = 529, group = "Other" },   -- Argent Dawn
    { id = 2586, group = "Other" },   -- Azeroth Commerce Authority
    { id = 2747, group = "Other" },   -- Barkskin Burrow
    { id = 87, group = "Other" },   -- Bloodsail Buccaneers
    { id = 2782, group = "Other" },   -- Bolder'ok Clan
    { id = 910, group = "Other" },   -- Brood of Nozdormu
    { id = 2826, group = "Other" },   -- Brotherhood of the Horse
    { id = 609, group = "Other" },   -- Cenarion Circle
    { id = 2719, group = "Other" },   -- Cenarion Scouts
    { id = 909, group = "Other" },   -- Darkmoon Faire
    { id = 2587, group = "Other" },   -- Durotar Supply and Logistics
    { id = 2787, group = "Other" },   -- Earthen Ring
    { id = 2641, group = "Other" },   -- Emerald Wardens
    { id = 92, group = "Other" },   -- Gelkis Clan Centaur
    { id = 2765, group = "Other" },   -- Guardians of Hyjal
    { id = 2779, group = "Other" },   -- High Order
    { id = 749, group = "Other" },   -- Hydraxian Waterlords
    { id = 2740, group = "Other" },   -- Kirin Tor
    { id = 93, group = "Other" },   -- Magram Clan Centaur
    { id = 2758, group = "Other" },   -- Nightclaw Druids
    { id = 630, group = "Other" },   -- Ravasaur Trainers
    { id = 349, group = "Other" },   -- Ravenholdt
    { id = 809, group = "Other" },   -- Shen'dralar
    { id = 70, group = "Other" },   -- Syndicate
    { id = 2819, group = "Other" },   -- The Watchers
    { id = 59, group = "Other" },   -- Thorium Brotherhood
    { id = 576, group = "Other" },   -- Timbermaw Hold
    { id = 471, group = "Other" },   -- Wildhammer Clan
    { id = 2778, group = "Other" },   -- Windshapers
    { id = 589, group = "Other" },   -- Wintersaber Trainers
    { id = 270, group = "Other" },   -- Zandalar Tribe
}

-- What the client says about a written-down faction, or nil where it is
-- not a reputation this character can hold: no such id, a header, the
-- other side's, or a creature faction (no description).
function Factions.Confirm(entry)
    if not (C_Reputation and C_Reputation.GetFactionDataByID) then return nil end
    if entry.side then
        local mine = UnitFactionGroup and UnitFactionGroup("player")
        if mine and mine ~= entry.side then return nil end
    end
    local ok, d = pcall(C_Reputation.GetFactionDataByID, entry.id)
    if not (ok and d and d.name and d.name ~= "") then return nil end
    if d.isHeader then return nil end
    if not d.description or d.description == "" then return nil end
    return d
end
