-- SPDX-License-Identifier: GPL-2.0-or-later
---------------------------------------------------------------------------
-- BazUI Codex: the instances there are
--
-- GENERATED by tools/gen-instances.py from the game's tables for build
-- 1.60.1.69893. Do not edit by hand; run the tool.
--
-- Every dungeon, raid and world boss the client knows about, with the
-- level it is tuned for, its player cap and its bosses in order. The
-- client will not list a place until you have been saved to it, and
-- Forever has no Encounter Journal, so this is where the Instances page
-- and Today's "for your level" block get the whole map from.
--
-- Names are the table's English. A lockout comes back from the client
-- in your language and is matched to these by name, so on another
-- language client the join may miss and the lockout is simply listed
-- on its own.
---------------------------------------------------------------------------

local Codex = BazUI.Codex
Codex.Instances = Codex.Instances or {}
local Instances = Codex.Instances

Instances.build = "1.60.1.69893"

Instances.entries = {
    -- dungeons
    {
        map = 389, name = "Ragefire Chasm", kind = "dungeon", players = 5, level = 13,
        bosses = {
            "Oggleflint",
            "Taragaman the Hungerer",
            "Jergosh the Invoker",
            "Bazzalan",
        },
    },
    {
        map = 3065, name = "The Hall of Thanes", kind = "dungeon", players = 5, level = 13, aliases = { "Hall of Thanes" },
        bosses = {
            "Faldrim Anvilmar",
            "Infurnus",
            "Plunder",
            "Durgen Dirgehammer",
        },
    },
    {
        map = 2999, name = "Ruins of Lordaeron", kind = "dungeon", players = 5, level = 15,
        bosses = {
            "Witherfang",
            "The Abandoned",
            "The Butcher",
            "Rath'mael",
            "Lordaeron Captain",
            "Viktor the Vile",
            "Bjork",
        },
    },
    {
        map = 36, name = "Deadmines", kind = "dungeon", players = 5, level = 16,
        bosses = {
            "Rhahk'Zor",
            "Sneed",
            "Gilnid",
            "Captain Greenskin",
            "Mr. Smite",
            "Cookie",
            "Edwin VanCleef",
        },
    },
    {
        map = 43, name = "Wailing Caverns", kind = "dungeon", players = 5, level = 17,
        bosses = {
            "Lady Anacondra",
            "Lord Cobrahn",
            "Kresh",
            "Lord Pythas",
            "Skum",
            "Lord Serpentis",
            "Verdan the Everliving",
            "Mutanus the Devourer",
        },
    },
    {
        map = 33, name = "Shadowfang Keep", kind = "dungeon", players = 5, level = 18,
        bosses = {
            "Rethilgore",
            "Razorclaw the Butcher",
            "Baron Silverlaine",
            "Commander Springvale",
            "Odo the Blindwatcher",
            "Fenrus the Devourer",
            "Wolf Master Nandos",
            "Archmage Arugal",
        },
    },
    {
        map = 48, name = "Blackfathom Deeps", kind = "dungeon", players = 5, level = 22,
        bosses = {
            "Ghamoo-ra",
            "Lady Sarevess",
            "Geilhast",
            "Lorgus Jett",
            "Old Serra'kis",
            "Twilight Lord Kelris",
            "Baron Aquanis",
            "Aku'mai",
            "Gelihast",
        },
    },
    {
        map = 34, name = "Stormwind Stockade", kind = "dungeon", players = 5, level = 23,
        bosses = {
            "Targorr the Dread",
            "Kam Deepfury",
            "Hamhock",
            "Dextren Ward",
            "Bazil Thredd",
        },
    },
    {
        map = 47, name = "Razorfen Kraul", kind = "dungeon", players = 5, level = 24,
        bosses = {
            "Roogug",
            "Aggem Thorncurse",
            "Death Speaker Jargba",
            "Overlord Ramtusk",
            "Agathelos the Raging",
            "Charlga Razorflank",
        },
    },
    {
        map = 90, name = "Gnomeregan", kind = "dungeon", players = 5, level = 25,
        bosses = {
            "Grubbis",
            "Viscous Fallout",
            "Electrocutioner 6000",
            "Crowd Pummeler 9-60",
            "Mekgineer Thermaplugg",
            "Mechanical Menagerie",
        },
    },
    {
        map = 2998, name = "Excavation Site: Wetlands", kind = "dungeon", players = 5, level = 26,
        bosses = {
            "Saltspine",
            "Shadetooth",
            "Highland Horror",
            "Relic Guardian",
        },
    },
    {
        map = 2959, name = "City of Dalaran", kind = "dungeon", players = 5, level = 28,
        bosses = {
            "Arcane Anomaly",
            "Fel Ancient",
            "Mana Devourer",
            "Mana Elemental",
            "Unstable Sentinel",
            "Shade of the Archmage",
            "Lyn the Ignored",
            "Atrexis the Grave Knight",
            "Mana Wraith",
        },
    },
    {
        map = 189, name = "Scarlet Monastery", kind = "dungeon", players = 5, level = 30, wings = { "Graveyard", "Armory", "Cathedral", "Library" }, aliases = { "Scarlet Monastery - Graveyard", "Scarlet Monastery - Armory", "Scarlet Monastery - Cathedral", "Scarlet Monastery - Library" },
        bosses = {
            "Interrogator Vishas",
            "Bloodmage Thalnos",
            "Houndmaster Loksey",
            "Arcanist Doan",
            "Herod",
            "High Inquisitor Fairbanks",
            "High Inquisitor Whitemane",
        },
    },
    {
        map = 129, name = "Razorfen Downs", kind = "dungeon", players = 5, level = 34,
        bosses = {
            "Tuten'kash",
            "Plaguemaw the Rotting",
            "Mordresh Fire Eye",
            "Ragglesnout",
            "Glutton",
            "Amnennar the Coldbringer",
        },
    },
    {
        map = 70, name = "Uldaman", kind = "dungeon", players = 5, level = 35,
        bosses = {
            "Revelosh",
            "The Lost Dwarves",
            "Ironaya",
            "Obsidian Sentinel",
            "Ancient Stone Keeper",
            "Galgann Firehammer",
            "Grimlok",
            "Archaedas",
        },
    },
    {
        map = 349, name = "Maraudon", kind = "dungeon", players = 5, level = 42,
        bosses = {
            "Noxxion",
            "Razorlash",
            "Tinkerer Gizlock",
            "Lord Vyletongue",
            "Celebras the Cursed",
            "Landslide",
            "Rotgrip",
            "Princess Theradras",
        },
    },
    {
        map = 209, name = "Zul'Farrak", kind = "dungeon", players = 5, level = 42,
        bosses = {
            "Hydromancer Velratha",
            "Gahz'rilla",
            "Antu'sul",
            "Theka the Martyr",
            "Witch Doctor Zum'rah",
            "Nekrum Gutchewer",
            "Shadowpriest Sezz'ziz",
            "Chief Ukorz Sandscalp",
        },
    },
    {
        map = 109, name = "Sunken Temple", kind = "dungeon", players = 5, level = 45,
        bosses = {
            "Avatar of Hakkar",
            "Atal'alarion",
            "Jammal'an the Prophet",
            "Dreamscythe",
            "Festering Rotslime",
            "Weaver",
            "Atal'ai Defenders",
            "Shade of Eranikus",
            "Dreamscythe and Weaver",
            "Hazzas",
            "Morphaz",
            "Jammal'an and Ogom",
            "Morphaz and Hazzas",
        },
    },
    {
        map = 230, name = "Blackrock Depths", kind = "dungeon", players = 5, level = 48,
        bosses = {
            "High Interrogator Gerstahn",
            "Lord Roccor",
            "Houndmaster Grebmar",
            "Ring of Law",
            "Pyromancer Loregrain",
            "Lord Incendius",
            "Warder Stilgiss",
            "Fineous Darkvire",
            "Bael'Gar",
            "General Angerforge",
            "Golem Lord Argelmach",
            "Hurley Blackbreath",
            "Phalanx",
            "Ribbly Screwspigot",
            "Plugger Spazzring",
            "The Vault",
            "Ambassador Flamelash",
            "The Seven",
            "Magmus",
            "Princess Moira Bronzebeard",
            "Emperor Dagran Thaurissan",
        },
    },
    {
        map = 229, name = "Blackrock Spire", kind = "dungeon", players = 5, level = 53, wings = { "Lower", "Upper" }, aliases = { "Lower Blackrock Spire", "Upper Blackrock Spire" },
        bosses = {
            "Highlord Omokk",
            "Shadow Hunter Vosh'gajin",
            "War Master Voone",
            "Mother Smolderweb",
            "Urok Doomhowl",
            "Quartermaster Zigris",
            "Halycon",
            "Gizrul the Slavener",
            "Overlord Wyrmthalak",
            "Pyroguard Emberseer",
            "Warchief Rend Blackhand",
            "The Beast",
            "General Drakkisath",
            "Lord Valthalak",
        },
    },
    {
        map = 429, name = "Dire Maul", kind = "dungeon", players = 5, level = 54, wings = { "East", "West", "North" }, aliases = { "Dire Maul (East)", "Dire Maul (West)", "Dire Maul (North)" },
        bosses = {
            "Zevrim Thornhoof",
            "Hydrospawn",
            "Lethtendris",
            "Pusillin",
            "Alzzin the Wildshaper",
            "Tendris Warpwood",
            "Illyanna Ravenoak",
            "Magister Kalendris",
            "Immol'thar",
            "Prince Tortheldrin",
            "Guard Mol'dar",
            "Stomper Kreeg",
            "Guard Fengus",
            "Guard Slip'kik",
            "Captain Kromcrush",
            "Cho'Rush the Observer",
            "King Gordok",
            "Lord Hel'nurath",
            "Tsu'zee",
        },
    },
    {
        map = 329, name = "Stratholme", kind = "dungeon", players = 5, level = 55, wings = { "Main Gate", "Service Gate" }, aliases = { "Stratholme (Main Gate)", "Stratholme (Service Gate)" },
        bosses = {
            "Hearthsinger Forresten",
            "Timmy the Cruel",
            "Malor the Zealous",
            "Cannon Master Willey",
            "Archivist Galford",
            "Balnazzar",
            "The Unforgiven",
            "Baroness Anastari",
            "Nerub'enkan",
            "Maleki the Pallid",
            "Magistrate Barthilas",
            "Ramstein the Gorger",
            "Baron Rivendare",
            "Black Guard Swordsmith",
            "Crimson Hammersmith",
            "Ezra Grimm",
            "Postmaster Malown",
            "Skul",
            "Stonespine",
        },
    },
    {
        map = 289, name = "Scholomance", kind = "dungeon", players = 5, level = 57,
        bosses = {
            "Kirtonos",
            "Jandice Barov",
            "Rattlegore",
            "Marduk Blackpool",
            "Vectus",
            "Kormok",
            "Ras Frostwhisperer",
            "Instructor Malicia",
            "Doctor Theolen Krastinov",
            "Lorekeeper Polkelt",
            "The Ravenian",
            "Lord Alexei Barov",
            "Lady Illucia Barov",
            "Darkmaster Gandling",
        },
    },
    {
        map = 2784, name = "Demon Fall Canyon", kind = "dungeon", players = 5,
        bosses = {
            "Grimroot",
            "Destructor's Wraith",
            "Zilbagob",
            "Pyranis",
            "Diathorus the Seeker",
            "Hellscream's Phantom",
            "Azgaloth",
        },
    },
    {
        map = 2875, name = "Karazhan Crypts", kind = "dungeon", players = 5,
        bosses = {
            "Harbinger of Sin",
            "Creeping Malison",
            "Three Little Wolves",
            "Dark Rider",
            "Kharon",
            "Unk'omon",
            "Hans and Greta",
            "The Ugly Goblin",
            "Kaigy Maryla",
            "Sairuh Maryla",
            "Barian Maryla",
        },
    },

    -- raids
    {
        map = 531, name = "Ahn'Qiraj Temple", kind = "raid", players = 40, level = 60,
        bosses = {
            "The Prophet Skeram",
            "Silithid Royalty",
            "Battleguard Sartura",
            "Fankriss the Unyielding",
            "Viscidus",
            "Princess Huhuran",
            "Twin Emperors",
            "Ouro",
            "C'thun",
        },
    },
    {
        map = 469, name = "Blackwing Lair", kind = "raid", players = 40, level = 60,
        bosses = {
            "Razorgore the Untamed",
            "Vaelastrasz the Corrupt",
            "Broodlord Lashlayer",
            "Firemaw",
            "Ebonroc",
            "Flamegor",
            "Chromaggus",
            "Nefarian",
        },
    },
    {
        map = 409, name = "Molten Core", kind = "raid", players = 40, level = 60,
        bosses = {
            "Lucifron",
            "Magmadar",
            "Gehennas",
            "Garr",
            "Shazzrah",
            "Baron Geddon",
            "Sulfuron Harbinger",
            "Golemagg the Incinerator",
            "Majordomo Executus",
            "Ragnaros",
            "The Molten Core",
        },
    },
    {
        map = 533, name = "Naxxramas", kind = "raid", players = 40, level = 60,
        bosses = {
            "Anub'Rekhan",
            "Grand Widow Faerlina",
            "Maexxna",
            "Noth the Plaguebringer",
            "Heigan the Unclean",
            "Loatheb",
            "Instructor Razuvious",
            "Gothik the Harvester",
            "The Four Horsemen",
            "Patchwerk",
            "Grobbulus",
            "Gluth",
            "Thaddius",
            "Sapphiron",
            "Kel'Thuzad",
        },
    },
    {
        map = 249, name = "Onyxia's Lair", kind = "raid", players = 40, level = 60,
        bosses = {
            "Onyxia",
        },
    },
    {
        map = 509, name = "Ruins of Ahn'Qiraj", kind = "raid", players = 20, level = 60, aliases = { "Ahn'Qiraj Ruins" },
        bosses = {
            "Kurinnaxx",
            "General Rajaxx",
            "Moam",
            "Buru the Gorger",
            "Ayamiss the Hunter",
            "Ossirian the Unscarred",
        },
    },
    {
        map = 2856, name = "Scarlet Enclave", kind = "raid", players = 40, level = 60,
        bosses = {
            "Balnazzar",
            "Beatrix",
            "Beastmaster",
            "Solistrasza",
            "Mason",
            "Reborn Council",
            "Lillian Voss",
            "Caldoran",
        },
    },
    {
        map = 309, name = "Zul'Gurub", kind = "raid", players = 20, level = 60,
        bosses = {
            "High Priestess Jeklik",
            "High Priest Venoxis",
            "High Priestess Mar'li",
            "Bloodlord Mandokir",
            "Edge of Madness",
            "High Priest Thekal",
            "Gahz'ranka",
            "High Priestess Arlokk",
            "Jin'do the Hexxer",
            "Hakkar",
        },
    },

    -- worlds
    {
        map = 2832, name = "Nightmare Grove", kind = "world", players = 40, level = 60,
        bosses = {
            "Emeriss",
            "Lethon",
            "Taerar",
            "Ysondre",
        },
    },
    {
        map = 2791, name = "Storm Cliffs", kind = "world", players = 40, level = 60,
        bosses = {
            "Azuregos",
        },
    },
    {
        map = 2804, name = "The Crystal Vale", kind = "world", players = 40, level = 60,
        bosses = {
            "Prince Thunderaan",
        },
    },
    {
        map = 2789, name = "The Tainted Scar", kind = "world", players = 40, level = 60,
        bosses = {
            "Lord Kazzak",
        },
    },
}

-- The catalogue entry a lockout belongs to, by name.
function Instances.ByName(name)
    if not name then return nil end
    for _, e in ipairs(Instances.entries) do
        if Codex.Gates.Same(e.name, name) then return e end
        for _, alias in ipairs(e.aliases or {}) do
            if Codex.Gates.Same(alias, name) then return e end
        end
    end
    return nil
end
